# Generated by Django 3.2.16 on 2024-01-30 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20240130_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='blog.post', verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(help_text='Формат даты: День.Месяц.Год<br/>Пример: 20.10.2020<br/>Если установить дату и время в будущем — можно делать отложенные публикации.', verbose_name='Дата и время публикации'),
        ),
    ]
