# Generated by Django 3.2.16 on 2024-01-30 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
